[build-system]
requires = ["setuptools>=64.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["fleche"]
package-dir = {""  = "src"}

[tool.setuptools_scm]
version_file = "src/fleche/_version.py"

[project]
name = "fleche"
dynamic = ["version"]
authors = [
    { name="Marvin Poul", email="pmrv@posteo.de" },
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "BSD-3-Clause"
dependencies = [
    'numpy',
    'pandas >= 2.2, <4',
    'pyiron-snippets',
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autoapi",
]
cloudpickle = [
    "cloudpickle",
]
sqlalchemy = [
    "sqlalchemy",
]
bagofholding = [
    "bagofholding == 0.1.9",
]
tests = [
    "pytest",
    "hypothesis",
    "cloudpickle",
    "sqlalchemy",
    "bagofholding == 0.1.9",
    "nbconvert",
    "ipykernel",
]
