"""Generate sequence-diagram SVGs for fleche's storage and cache operations.

Outputs:
  storage_sequence.svg  -- a destructured save() and load() through the MRO
  cache_sequence.svg    -- the two-phase save protocol behind a decorated call

Run as a script (``python gen_sequence.py``) this writes the SVGs next to
itself.  The depicted call sequences are transcribed from real traces: the
storage panels come from instrumenting ``_operation_context``/``put``/``get``
on a ``ValueMemory`` subclass, so the lock scopes shown are the ones the code
actually takes, not a reading of it.

Palette is solarized light, matching the docs skin in docs/_static/custom.css
and the figures in gen_diagrams.py.

Panels are described declaratively; see the panels at the bottom for
the step vocabulary:

  ("call", src, dst, label)   a synchronous call, solid arrow
  ("ret",  src, dst, label)   a return, dashed arrow
  ("self", who, label)        a self-call, drawn as a loop on the lifeline
  ("note", label)             a full-width annotation between rows
  ("lock+", who, label)       open an activation bar on *who* at this row
  ("lock-", who)              close it
"""
import os

OUT = os.path.dirname(os.path.abspath(__file__))

# palette (solarized light, matching docs/_static/custom.css)
BLUE = "#268bd2"
TEAL = "#2aa198"
GREEN = "#859900"
VIOLET = "#6c71c4"
ORANGE = "#cb4b16"
ORANGE_PALE = "#f7e2d8"
INK = "#073642"       # base02
INK2 = "#586e75"      # base01
MUTED = "#93a1a1"     # base1
MID_INK = "#657b83"   # base00
HAIR = "#e7dfc9"
NEUTRAL = "#eee8d5"   # base2
SURFACE = "#fdf6e3"   # base3
WHITE = "#fefbf0"

GEN_NOTE = ("<!-- Generated by docs/figures/gen_sequence.py - edit the script "
            "and rerun it, not this file. -->")

SANS = "system-ui, -apple-system, 'Segoe UI', sans-serif"
MONO = "ui-monospace, 'Cascadia Code', Menlo, Consolas, monospace"

# geometry
PAD_X = 26
HEAD_Y = 34          # top of the lifeline header boxes
HEAD_H = 40
ROW0 = HEAD_Y + HEAD_H + 34
ROW = 34             # vertical distance between message rows
NOTE_ROW = 26        # a note consumes less height than a message
FOOT = 30
PANEL_GAP = 40
BAR_W = 9            # width of an activation bar


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def text(x, y, s, size=12, fill=INK, anchor="start", mono=False, weight=None,
         style=None):
    fam = MONO if mono else SANS
    w = f' font-weight="{weight}"' if weight else ""
    st = f' font-style="{style}"' if style else ""
    return (f'<text x="{x:.1f}" y="{y:.1f}" font-family="{fam}" font-size="{size}" '
            f'fill="{fill}" text-anchor="{anchor}"{w}{st}>{esc(s)}</text>')


DEFS = f'''<defs>
<marker id="seq-call" viewBox="0 0 9 9" refX="8" refY="4.5" markerWidth="7"
        markerHeight="7" orient="auto">
  <path d="M0 0 L9 4.5 L0 9 z" fill="{INK2}"/>
</marker>
<marker id="seq-ret" viewBox="0 0 9 9" refX="8" refY="4.5" markerWidth="6.5"
        markerHeight="6.5" orient="auto">
  <path d="M0 0.5 L9 4.5 L0 8.5" fill="none" stroke="{MID_INK}"
        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</marker>
</defs>'''


class Panel:
    """One sequence diagram: a title, a set of lifelines, and ordered steps."""

    def __init__(self, title, subtitle, lifelines, steps):
        self.title = title
        self.subtitle = subtitle
        self.lifelines = lifelines          # list of (key, label, accent)
        self.steps = steps

    # -- layout ------------------------------------------------------------
    def x_of(self, key, col_w, x0):
        keys = [k for k, _, _ in self.lifelines]
        return x0 + keys.index(key) * col_w + col_w / 2

    def height(self):
        y = ROW0
        for step in self.steps:
            if step[0] == "note":
                y += NOTE_ROW
            elif step[0] in ("lock+", "lock-"):
                continue
            else:
                y += ROW
        return y + FOOT

    def render(self, x0, y0, col_w):
        out = []
        n = len(self.lifelines)
        w = n * col_w

        # panel title
        out.append(text(x0, y0 + 16, self.title, 14, INK, weight="700"))
        if self.subtitle:
            out.append(text(x0 + 8 + len(self.title) * 8.2, y0 + 16,
                            self.subtitle, 11.5, MID_INK, style="italic"))

        # walk the steps once to find row positions and bar extents
        rows = []            # y of each drawable step, aligned with self.steps
        y = y0 + ROW0
        for step in self.steps:
            if step[0] == "note":
                rows.append(y)
                y += NOTE_ROW
            elif step[0] == "lock-":
                # close well above the next row and open well below it, so two
                # back-to-back scopes read as two bars rather than one.
                rows.append(y - ROW * 0.66)
            elif step[0] == "lock+":
                rows.append(y - ROW * 0.20)
            else:
                rows.append(y)
                y += ROW
        bottom = y + 6

        # lifelines + headers
        for key, label, accent in self.lifelines:
            x = self.x_of(key, col_w, x0)
            out.append(f'<line x1="{x:.1f}" y1="{y0 + HEAD_Y + HEAD_H:.1f}" '
                       f'x2="{x:.1f}" y2="{bottom:.1f}" stroke="{MUTED}" '
                       f'stroke-width="1.2" stroke-dasharray="4 4"/>')
            bw = col_w - 16
            out.append(f'<rect x="{x - bw / 2:.1f}" y="{y0 + HEAD_Y:.1f}" '
                       f'width="{bw:.1f}" height="{HEAD_H}" rx="7" fill="{WHITE}" '
                       f'stroke="{accent}" stroke-width="1.5"/>')
            lines = label.split("\n")
            ty = y0 + HEAD_Y + (HEAD_H / 2) + (5 if len(lines) == 1 else -2)
            for i, ln in enumerate(lines):
                out.append(text(x, ty + i * 12.5, ln, 11.5 if i == 0 else 10,
                                INK if i == 0 else MID_INK, anchor="middle",
                                mono=(i == 0), weight="600" if i == 0 else None))

        # activation bars
        open_bars = {}
        for i, step in enumerate(self.steps):
            if step[0] == "lock+":
                open_bars[step[1]] = (rows[i], step[2])
            elif step[0] == "lock-":
                start, label = open_bars.pop(step[1])
                x = self.x_of(step[1], col_w, x0)
                end = rows[i]
                out.append(f'<rect x="{x - BAR_W / 2:.1f}" y="{start:.1f}" '
                           f'width="{BAR_W}" height="{max(end - start, 8):.1f}" rx="3" '
                           f'fill="{ORANGE_PALE}" stroke="{ORANGE}" stroke-width="1.3"/>')
                out.append(text(x + BAR_W / 2 + 6, start + 11, label, 10,
                                ORANGE, mono=True))

        # messages
        for i, step in enumerate(self.steps):
            kind = step[0]
            y = rows[i]
            if kind == "note":
                # pill behind the text so it reads over the dashed lifelines
                tw = len(step[1]) * 5.1 + 18
                cx = x0 + w / 2
                out.append(f'<rect x="{cx - tw / 2:.1f}" y="{y - 8:.1f}" '
                           f'width="{tw:.1f}" height="17" rx="8.5" fill="{NEUTRAL}" '
                           f'stroke="{HAIR}" stroke-width="1"/>')
                out.append(text(cx, y + 4, step[1], 10.5, MID_INK,
                                anchor="middle", style="italic"))
            elif kind == "self":
                x = self.x_of(step[1], col_w, x0)
                r = 13
                out.append(f'<path d="M {x + BAR_W / 2:.1f} {y - 8:.1f} '
                           f'h {r} v {r} h -{r}" fill="none" stroke="{INK2}" '
                           f'stroke-width="1.4" marker-end="url(#seq-call)"/>')
                out.append(text(x + BAR_W / 2 + r + 8, y + 1, step[2], 10.5, INK,
                                mono=True))
            elif kind in ("call", "ret"):
                xs = self.x_of(step[1], col_w, x0)
                xd = self.x_of(step[2], col_w, x0)
                sign = 1 if xd > xs else -1
                xs += sign * BAR_W / 2
                xd -= sign * (BAR_W / 2 + 3)
                dash = ' stroke-dasharray="5 4"' if kind == "ret" else ""
                color = MID_INK if kind == "ret" else INK2
                marker = "seq-ret" if kind == "ret" else "seq-call"
                out.append(f'<line x1="{xs:.1f}" y1="{y:.1f}" x2="{xd:.1f}" '
                           f'y2="{y:.1f}" stroke="{color}" stroke-width="1.4"'
                           f'{dash} marker-end="url(#{marker})"/>')
                mid = (xs + xd) / 2
                out.append(text(mid, y - 7, step[3], 10.5,
                                INK if kind == "call" else MID_INK,
                                anchor="middle", mono=True))
        return out


def render(panels, col_w=196):
    n = max(len(p.lifelines) for p in panels)
    w = n * col_w + 2 * PAD_X
    heights = [p.height() for p in panels]
    h = sum(heights) + PANEL_GAP * (len(panels) - 1) + 10

    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" '
             f'height="{h:.0f}" viewBox="0 0 {w:.0f} {h:.0f}" '
             f'font-family="{SANS}">', GEN_NOTE, DEFS,
             f'<rect width="{w:.0f}" height="{h:.0f}" fill="{SURFACE}"/>']

    y = 4
    for i, panel in enumerate(panels):
        if i:
            parts.append(f'<line x1="{PAD_X}" y1="{y - PANEL_GAP / 2:.1f}" '
                         f'x2="{w - PAD_X}" y2="{y - PANEL_GAP / 2:.1f}" '
                         f'stroke="{HAIR}" stroke-width="1.5"/>')
        x0 = PAD_X + (n - len(panel.lifelines)) * col_w / 2
        parts += panel.render(x0, y, col_w)
        y += heights[i] + PANEL_GAP

    parts.append("</svg>")
    return "\n".join(parts)


# ------------------------------------------------------- storage sequences
#
# Transcribed from an instrumented ValueMemory: see the module docstring.
# `CALLER`/`DM`/`VM`/`BE`/`DISK` are lifeline keys.

_STORAGE_LIFELINES = [
    ("CALLER", "caller", MID_INK),
    ("DM", "DestructuringMixin\nposition 2", ORANGE),
    ("VM", "ValueMixin\nposition 3", "#b58900"),
    ("BE", "PickleFileBackend\n+ FileStorage", MID_INK),
    ("DISK", "disk", MUTED),
]

STORAGE_SAVE = Panel(
    "save([1, [2, 3]])",
    "one lock per entry, children first",
    _STORAGE_LIFELINES,
    [
        ("call", "CALLER", "DM", "save([1, [2, 3]])"),
        ("self", "DM", "_intern_rec: walk to the leaves"),
        ("note", "stored via super().save() - the child does not re-enter DestructuringMixin"),
        ("lock+", "VM", "RLock(ed76af)"),
        ("call", "DM", "VM", "super().save([2, 3])"),
        ("call", "VM", "BE", "put([2, 3], ed76af)"),
        ("call", "BE", "DISK", "pickle, sign, rename"),
        ("ret", "VM", "DM", "ed76af"),
        ("lock-", "VM"),
        ("lock+", "VM", "RLock(2f6b57)"),
        ("call", "DM", "VM", "super().save(Digested(...))"),
        ("call", "VM", "BE", "put(..., 2f6b57)"),
        ("call", "BE", "DISK", "pickle, sign, rename"),
        ("ret", "VM", "DM", "2f6b57"),
        ("lock-", "VM"),
        ("ret", "DM", "CALLER", "2f6b57"),
        ("note", "the two lock scopes are disjoint: no lock is held across the walk"),
    ],
)

STORAGE_LOAD = Panel(
    "load(2f6b57)",
    "the parent's lock is released before the child is fetched",
    _STORAGE_LIFELINES,
    [
        ("call", "CALLER", "DM", "load(2f6b57)"),
        ("lock+", "VM", "RLock(2f6b57)"),
        ("call", "DM", "VM", "super().load(2f6b57)"),
        ("call", "VM", "BE", "get(2f6b57)"),
        ("call", "BE", "DISK", "read, verify, unpickle"),
        ("ret", "VM", "DM", "Digested([1, ed76af])"),
        ("lock-", "VM"),
        ("self", "DM", ".mend(self)"),
        ("note", "mend calls the PUBLIC load, so the child does re-enter DestructuringMixin"),
        ("lock+", "VM", "RLock(ed76af)"),
        ("call", "DM", "VM", "super().load(ed76af)"),
        ("call", "VM", "BE", "get(ed76af)"),
        ("call", "BE", "DISK", "read, verify, unpickle"),
        ("ret", "VM", "DM", "[2, 3]"),
        ("lock-", "VM"),
        ("ret", "DM", "CALLER", "[1, [2, 3]]"),
    ],
)

# --------------------------------------------------------- cache sequence

_CACHE_LIFELINES = [
    ("USER", "caller", MUTED),
    ("W", "@fleche wrapper", MID_INK),
    ("C", "Cache", GREEN),
    ("V", "values\nValueStorage", TEAL),
    ("K", "calls\nCallStorage", BLUE),
    ("F", "your function", VIOLET),
]

CACHE_MISS = Panel(
    "cache miss",
    "the two-phase save protocol",
    _CACHE_LIFELINES,
    [
        ("call", "USER", "W", "f(x)"),
        ("self", "W", "key = call.to_lookup_key()"),
        ("call", "W", "C", "load(key)"),
        ("ret", "C", "W", "KeyError -- miss"),
        ("note", "phase 1 - seal the identity, and stash the arguments, BEFORE the body runs"),
        ("call", "W", "C", "prepare(call)"),
        ("call", "C", "V", "save(x) for each arg"),
        ("ret", "C", "W", "PreparedCall"),
        ("call", "W", "F", "f(x)"),
        ("ret", "F", "W", "result"),
        ("note", "the body may mutate x here - the sealed key already predates it"),
        ("note", "phase 2 - the arguments are NOT re-saved; only the result is"),
        ("call", "W", "C", "commit(result) -> cache.save"),
        ("call", "C", "V", "resolve(): save(result)"),
        ("call", "C", "K", "save(DigestedCall)"),
        ("ret", "C", "W", "key"),
        ("ret", "W", "USER", "result"),
        ("note", "on an exception in the body the wrapper calls abandon() instead"),
    ],
)

CACHE_HIT = Panel(
    "cache hit",
    "no preparation, no function call",
    _CACHE_LIFELINES,
    [
        ("call", "USER", "W", "f(x)"),
        ("self", "W", "key = call.to_lookup_key()"),
        ("call", "W", "C", "load(key)"),
        ("call", "C", "K", "load(key)"),
        ("ret", "C", "W", "LazyCall (holds the cache)"),
        ("call", "W", "C", "lazy.result"),
        ("call", "C", "V", "load_value(result digest)"),
        ("ret", "C", "W", "result"),
        ("ret", "W", "USER", "result"),
        ("note", "the LazyCall resolves argument and result digests on attribute access"),
    ],
)


if __name__ == "__main__":
    for name, panels, col_w in (
        ("storage_sequence", [STORAGE_SAVE, STORAGE_LOAD], 208),
        ("cache_sequence", [CACHE_MISS, CACHE_HIT], 186),
    ):
        path = os.path.join(OUT, f"{name}.svg")
        with open(path, "w") as fh:
            fh.write(render(panels, col_w=col_w))
            fh.write("\n")
        print(f"wrote {path}")
