"""Generate documentation SVGs for fleche storage destructuring.

Outputs:
  dedup_forest.svg     -- two nested values -> flat deduplicated forest of entries
  remaining_depth.svg  -- how remaining_depth partitions a tree into entries
  special_cases.svg    -- opaque objects (depth inf), namedtuples, empty containers

Run as a script (``python gen_diagrams.py``) this writes the three SVGs next to
itself, with real digest labels computed by ``real_hashes()``: the depicted
layouts are built in actual ``ValueMemory`` stores and each entry key is
shortened with fleche's own ``shrink``.  Because digests are content-addressed,
readers reproducing the layouts (see ``notebooks/Destructuring.ipynb``) get
exactly the digests shown in the figures.

Hash injection: each figure function takes an optional ``hashes`` mapping of
entry anchors to short digest strings, rendered as small mono labels next to
the corresponding storage-entry blob.  Omitted anchors get no label, so a
subset is fine.  Content addressing means an entry's digest is the same at
every remaining_depth, so one mapping serves all four panels.

  svg_dedup(hashes={"xs": ..., "ys": ..., "shared": ...})
      defaults to the placeholder digests shown in the figure.
  svg_depth(hashes={"root": ..., "L": ..., "R": ..., "S": ...,
                    "1": ..., ..., "5": ...})
      anchor = topmost node of a blob (the node the entry is stored under);
      default None renders no digest labels.
  svg_special(hashes={"opaque": {"root": ..., "A": ...},
                      "propagate": {"root": ..., "M": ..., "A": ...},
                      "namedtuple": {"root": ..., "T": ..., "P": ...},
                      "empty": {"root": ...}})
      one sub-mapping per panel; default None renders no digest labels.
"""
import math
import os

OUT = os.path.dirname(os.path.abspath(__file__))

# palette (dataviz reference, light mode)
BLUE = "#2a78d6"
BLUE_DEEP = "#1c5cab"
BLUE_MID = "#86b6ef"
BLUE_PALE = "#cde2fb"
ORANGE = "#eb6834"
ORANGE_DEEP = "#b34a17"
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"
MID_INK = "#6d6c67"  # between MUTED and INK2: digest labels and depth badges
EDGE = "#b9b8b0"
HAIR = "#e1e0d9"
NEUTRAL = "#f0efec"
SURFACE = "#fcfcfb"
WHITE = "#ffffff"

GEN_NOTE = ("<!-- Generated by docs/figures/gen_diagrams.py - edit the script "
            "and rerun it, not this file. -->")

SANS = "system-ui, -apple-system, 'Segoe UI', sans-serif"
MONO = "ui-monospace, 'Cascadia Code', Menlo, Consolas, monospace"


def text(x, y, s, size=12, fill=INK, anchor="start", mono=False, weight=None):
    fam = MONO if mono else SANS
    w = f' font-weight="{weight}"' if weight else ""
    return (f'<text x="{x}" y="{y}" font-family="{fam}" font-size="{size}" '
            f'fill="{fill}" text-anchor="{anchor}"{w}>{s}</text>')


def badge(x, y, s, anchor="start"):
    """Depth annotation next to a node (``d=0`` .. ``d=inf``)."""
    return text(x, y, s, 12.5, MID_INK, anchor=anchor, mono=True, weight="600")


def trim(p, q, tp, tq):
    dx, dy = q[0] - p[0], q[1] - p[1]
    length = math.hypot(dx, dy)
    ux, uy = dx / length, dy / length
    return ((p[0] + ux * tp, p[1] + uy * tp), (q[0] - ux * tq, q[1] - uy * tq))


def line(p, q, color=EDGE, width=1.6, marker=None):
    m = f' marker-end="url(#{marker})"' if marker else ""
    return (f'<line x1="{p[0]:.1f}" y1="{p[1]:.1f}" x2="{q[0]:.1f}" y2="{q[1]:.1f}" '
            f'stroke="{color}" stroke-width="{width}"{m}/>')


def scalar_node(x, y, label, r=11, stroke=MUTED, fs=11):
    return (f'<circle cx="{x}" cy="{y}" r="{r}" fill="{WHITE}" stroke="{stroke}" '
            f'stroke-width="1.3"/>'
            + text(x, y + fs * 0.36, label, size=fs, anchor="middle", mono=True))


def container_node(x, y, w=30, h=20, stroke=INK2, fs=10, label="[ ]"):
    return (f'<rect x="{x - w / 2}" y="{y - h / 2}" width="{w}" height="{h}" rx="6" '
            f'fill="{WHITE}" stroke="{stroke}" stroke-width="1.3"/>'
            + text(x, y + fs * 0.36, label, size=fs, anchor="middle", mono=True))


def opaque_node(x, y, w=32, h=20, fs=9.5, label="arr"):
    return (f'<rect x="{x - w / 2}" y="{y - h / 2}" width="{w}" height="{h}" rx="6" '
            f'fill="{NEUTRAL}" stroke="{MUTED}" stroke-width="1.3" '
            f'stroke-dasharray="3 2.5"/>'
            + text(x, y + fs * 0.36, label, size=fs, fill=INK2, anchor="middle", mono=True))


def blob_paths(polylines, width=38):
    d = ""
    for pts in polylines:
        d += (f'M {pts[0][0]:.1f} {pts[0][1]:.1f} '
              + " ".join(f'L {x:.1f} {y:.1f}' for x, y in pts[1:]) + " ")
    common = 'fill="none" stroke-linecap="round" stroke-linejoin="round"'
    border = f'<path d="{d.strip()}" {common} stroke="{BLUE_MID}" stroke-width="{width + 5}"/>'
    fill = f'<path d="{d.strip()}" {common} stroke="{BLUE_PALE}" stroke-width="{width}"/>'
    return border, fill


DEFS = f'''<defs>
<marker id="arr-blue" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto">
  <path d="M0 0 L8 4 L0 8 z" fill="{BLUE_DEEP}"/>
</marker>
<marker id="arr-ink" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto">
  <path d="M0 0 L8 4 L0 8 z" fill="{INK2}"/>
</marker>
</defs>'''


# ---------------------------------------------------------------- SVG 1: dedup

def svg_dedup(hashes=None, background=True):
    h = {"xs": "3f6c&#8230;", "ys": "b21d&#8230;", "shared": "9c2e&#8230;"}
    if hashes:
        h.update(hashes)
    W, H = 920, 364
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
           f'font-family="{SANS}">', GEN_NOTE, DEFS]
    if background:
        out.append(f'<rect width="{W}" height="{H}" fill="{SURFACE}"/>')
    out.append('<g transform="translate(0,-72)">')

    # ---- left panel: the two Python values as trees
    out.append(text(24, 96, "What you save", 13, INK, weight="600"))
    out.append(text(130, 96, "(two nested values)", 11.5, MUTED))

    trees = {}
    for name, dx, root_lbl, s_lbl in (("A", 0, "xs = [1, [2, 3]]", "1"),
                                      ("B", 205, "ys = [4, [2, 3]]", "4")):
        n = {"root": (105 + dx, 155), "s": (60 + dx, 228), "sub": (152 + dx, 228),
             "l2": (122 + dx, 298), "l3": (184 + dx, 298)}
        trees[name] = n
        # orange wash behind the shared sub-tree
        out.append(f'<rect x="{99 + dx}" y="{209}" width="108" height="110" rx="14" '
                   f'fill="{ORANGE}" fill-opacity="0.07" stroke="{ORANGE}" '
                   f'stroke-opacity="0.55" stroke-width="1.2" stroke-dasharray="5 4"/>')
        out.append(text(105 + dx, 124, root_lbl, 12.5, INK, anchor="middle", mono=True))
        for a, b, ta, tb in (("root", "s", 18, 17), ("root", "sub", 18, 17),
                             ("sub", "l2", 17, 17), ("sub", "l3", 17, 17)):
            p, q = trim(n[a], n[b], ta, tb)
            out.append(line(p, q, EDGE, 1.5))
        out.append(container_node(*n["root"], w=40, h=26, fs=11))
        out.append(scalar_node(*n["s"], s_lbl, r=15, fs=12.5))
        out.append(container_node(*n["sub"], w=40, h=26, stroke=ORANGE, fs=11))
        out.append(scalar_node(*n["l2"], "2", r=15, stroke=ORANGE, fs=12.5))
        out.append(scalar_node(*n["l3"], "3", r=15, stroke=ORANGE, fs=12.5))

    out.append(text(255, 345, "identical sub-value", 11.5, ORANGE_DEEP, anchor="middle"))
    out.append(text(255, 361, "same content &#8658; same digest", 11.5, ORANGE_DEEP, anchor="middle"))

    # ---- middle: save / load arrows
    out.append(text(474, 180, "save()", 12.5, INK, anchor="middle", mono=True, weight="600"))
    out.append(line((430, 192), (516, 192), INK2, 1.7, marker="arr-ink"))
    out.append(text(474, 210, "hash &amp; split", 11, MUTED, anchor="middle"))
    out.append(text(474, 246, "load()", 12.5, INK, anchor="middle", mono=True, weight="600"))
    out.append(line((516, 258), (430, 258), INK2, 1.7, marker="arr-ink"))
    out.append(text(474, 276, "mend", 11, MUTED, anchor="middle"))

    # ---- right panel: the stored forest, one blob per entry
    out.append(text(530, 96, "What storage holds", 13, INK, weight="600"))
    out.append(text(668, 96, "(flat forest of entries)", 11.5, MUTED))

    ent_a = {"root": (612, 150), "s": (577, 215)}
    ent_b = {"root": (848, 150), "s": (883, 215)}
    shared = {"root": (730, 290), "l2": (697, 355), "l3": (763, 355)}

    for pls in ([[ent_a["s"], ent_a["root"]]], [[ent_b["s"], ent_b["root"]]],
                [[shared["l2"], shared["root"], shared["l3"]]]):
        b, f = blob_paths(pls, width=48)
        out += [b, f]

    out.append(text(612, 120, h["xs"], 12, MID_INK, anchor="middle", mono=True))
    out.append(text(848, 120, h["ys"], 12, MID_INK, anchor="middle", mono=True))

    for tree, pairs in ((ent_a, [("root", "s")]), (ent_b, [("root", "s")]),
                        (shared, [("root", "l2"), ("root", "l3")])):
        for a, b in pairs:
            p, q = trim(tree[a], tree[b], 17, 17)
            out.append(line(p, q, EDGE, 1.5))

    # digest-reference arrows from both roots to the single shared entry
    for ent in (ent_a, ent_b):
        p, q = trim(ent["root"], shared["root"], 33, 35)
        out.append(line(p, q, BLUE_DEEP, 1.7, marker="arr-blue"))

    out.append(container_node(*ent_a["root"], w=40, h=26, fs=11))
    out.append(scalar_node(*ent_a["s"], "1", r=15, fs=12.5))
    out.append(container_node(*ent_b["root"], w=40, h=26, fs=11))
    out.append(scalar_node(*ent_b["s"], "4", r=15, fs=12.5))
    out.append(container_node(*shared["root"], w=40, h=26, stroke=ORANGE, fs=11))
    out.append(scalar_node(*shared["l2"], "2", r=15, stroke=ORANGE, fs=12.5))
    out.append(scalar_node(*shared["l3"], "3", r=15, stroke=ORANGE, fs=12.5))

    out.append(text(730, 402, h["shared"], 12, ORANGE_DEEP, anchor="middle", mono=True))
    out.append(text(730, 420, "stored once, referenced twice", 11.5, ORANGE_DEEP, anchor="middle"))

    out.append("</g>")
    out.append("</svg>")
    return "\n".join(out)


# ------------------------------------------------- SVG 2: remaining_depth

MINI = {"root": ("c", 145, 62), "L": ("c", 70, 122), "R": ("c", 214, 122),
        "1": ("s", 36, 182), "2": ("s", 102, 182), "3": ("s", 170, 182),
        "S": ("c", 246, 182), "4": ("s", 212, 242), "5": ("s", 280, 242)}
EDGES = [("root", "L"), ("root", "R"), ("L", "1"), ("L", "2"),
         ("R", "3"), ("R", "S"), ("S", "4"), ("S", "5")]
SCALAR_LBL = {"1": "1", "2": "2", "3": "3", "4": "4", "5": "5"}
# where an injected digest label sits relative to its anchor node, chosen to
# dodge the incoming edge: (dx, dy, text-anchor)
HASH_POS = {"root": (0, -30, "middle"), "L": (-16, -26, "end"), "R": (16, -26, "start"),
            "S": (16, -26, "start"), "1": (0, 32, "middle"), "2": (0, 32, "middle"),
            "3": (0, 32, "middle"), "4": (0, 32, "middle"), "5": (0, 32, "middle")}


def mini_pt(name, ox, oy):
    _, x, y = MINI[name]
    return (x + ox, y + oy)


def poly(ox, oy, *names):
    pts = []
    for nm in names:
        kind, x, y = MINI[nm]
        pts.append((x + ox, y + oy))
    if len(pts) == 1:
        (x, y) = pts[0]
        half = 9 if MINI[names[0]][0] in ("c", "o") else 0.01
        pts = [(x - half, y), (x + half, y)]
    return pts


def panel(ox, oy, depth, count, blobs, blue_edges, trims=None, hashes=None):
    """blobs: list of ``(anchor, polylines)`` — anchor is the node the entry is
    stored under; when *hashes* provides a digest for it, a label is drawn."""
    out = [text(ox + 2, oy + 16, f"remaining_depth = {depth}", 13, INK, mono=True, weight="600"),
           text(ox + 288, oy + 16, count, 12, BLUE_DEEP, anchor="end", weight="600")]
    borders, fills = [], []
    for _, polylines in blobs:
        b, f = blob_paths(polylines)
        borders.append(b)
        fills.append(f)
    out += borders + fills
    for a, b in EDGES:
        p, q = mini_pt(a, ox, oy), mini_pt(b, ox, oy)
        if (a, b) in blue_edges:
            ta, tb = (trims or {}).get((a, b), (26, 27))
            tp, tq = trim(p, q, ta, tb)
            out.append(line(tp, tq, BLUE_DEEP, 1.7, marker="arr-blue"))
        else:
            tp, tq = trim(p, q, 12, 12)
            out.append(line(tp, tq, EDGE, 1.6))
    for nm, (kind, x, y) in MINI.items():
        if kind == "c":
            out.append(container_node(x + ox, y + oy))
        elif kind == "o":
            out.append(opaque_node(x + ox, y + oy))
        else:
            out.append(scalar_node(x + ox, y + oy, SCALAR_LBL[nm]))
    if hashes:
        for anchor, _ in blobs:
            if anchor in hashes:
                _, x, y = MINI[anchor]
                dx, dy, anc = HASH_POS[anchor]
                out.append(text(x + dx + ox, y + dy + oy, hashes[anchor], 12, MID_INK,
                                anchor=anc, mono=True))
    return out


def svg_depth(hashes=None, background=True):
    W, H = 1000, 626
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
           f'font-family="{SANS}">', GEN_NOTE, DEFS]
    if background:
        out.append(f'<rect width="{W}" height="{H}" fill="{SURFACE}"/>')
    out.append('<g transform="translate(0,-64)">')

    # ---- left: reference tree with depth badges
    out.append(text(24, 112, "The value", 13, INK, weight="600"))
    out.append(text(24, 132, "[[1, 2], [3, [4, 5]]]", 13, INK, mono=True))

    ref = {"root": ("c", 160, 175), "L": ("c", 85, 247), "R": ("c", 240, 247),
           "1": ("s", 50, 319), "2": ("s", 120, 319), "3": ("s", 200, 319),
           "S": ("c", 275, 319), "4": ("s", 240, 391), "5": ("s", 310, 391)}
    for a, b in EDGES:
        pa, pb = ref[a][1:], ref[b][1:]
        ta = 20 if ref[a][0] == "c" else 16
        tb = 18 if ref[b][0] == "c" else 16
        p, q = trim(pa, pb, ta, tb)
        out.append(line(p, q, EDGE, 1.5))
    for nm, (kind, x, y) in ref.items():
        if kind == "c":
            out.append(container_node(x, y, w=36, h=24, fs=11))
        else:
            out.append(scalar_node(x, y, SCALAR_LBL[nm], r=13, fs=12))
    depths = {"root": 3, "L": 1, "R": 2, "1": 0, "2": 0, "3": 0, "S": 1, "4": 0, "5": 0}
    badge_pos = {"root": (186, 168, "start"), "L": (60, 240, "end"), "R": (266, 240, "start"),
                 "1": (50, 345, "middle"), "2": (120, 345, "middle"), "3": (200, 345, "middle"),
                 "S": (299, 312, "start"), "4": (216, 384, "end"), "5": (332, 384, "start")}
    for nm, (x, y, anchor) in badge_pos.items():
        out.append(badge(x, y, f"d={depths[nm]}", anchor))

    # rule box
    out.append(f'<rect x="24" y="430" width="306" height="58" rx="8" fill="{NEUTRAL}"/>')
    out.append(text(36, 453, "depth &lt; remaining_depth &#8594; inline in parent", 11.5, INK2, mono=True))
    out.append(text(36, 473, "depth &#8805; remaining_depth &#8594; entry of its own", 11.5, INK2, mono=True))

    # legend
    b, f = blob_paths([[(34, 543), (64, 543)]], width=22)
    out += [b, f]
    out.append(text(80, 547, "one storage entry", 11.5, INK2))
    out.append(line((30, 575), (64, 575), BLUE_DEEP, 1.7, marker="arr-blue"))
    out.append(text(80, 579, "&lt;digest&gt; reference to a child entry", 11.5, INK2))
    out.append(line((30, 603), (64, 603), EDGE, 1.6))
    out.append(text(80, 607, "inlined child (same entry)", 11.5, INK2))

    # ---- right: 2x2 grid of partitions
    grid = [(370, 100, 0), (690, 100, 1), (370, 400, 2), (690, 400, 3)]
    spec = {
        0: ("9 entries",
            lambda ox, oy: [(n, [poly(ox, oy, n)]) for n in MINI],
            set(EDGES), None),
        1: ("4 entries",
            lambda ox, oy: [("root", [poly(ox, oy, "root")]),
                            ("L", [poly(ox, oy, "1", "L", "2")]),
                            ("R", [poly(ox, oy, "3", "R")]),
                            ("S", [poly(ox, oy, "4", "S", "5")])],
            {("root", "L"), ("root", "R"), ("R", "S")}, None),
        2: ("2 entries",
            lambda ox, oy: [("root", [poly(ox, oy, "1", "L", "2"), poly(ox, oy, "L", "root")]),
                            ("R", [poly(ox, oy, "3", "R"), poly(ox, oy, "4", "S", "5"),
                                   poly(ox, oy, "R", "S")])],
            {("root", "R")}, None),
        3: ("1 entry",
            lambda ox, oy: [("root", [poly(ox, oy, a, b) for a, b in EDGES])],
            set(), None),
    }
    for ox, oy, d in grid:
        count, blobs_fn, blue, trims = spec[d]
        out += panel(ox, oy, d, count, blobs_fn(ox, oy), blue, trims, hashes)

    out.append("</g>")
    out.append("</svg>")
    return "\n".join(out)


# ------------------------------------------------- SVG 3: special cases

def vignette(ox, oy, title, count, value_str, nodes, edges, blobs, blue, badges,
             hash_pos=None, hashes=None):
    """One special-case panel: nodes = {name: (kind, x, y, label)}, blobs = entries
    as (anchor, polylines) with polylines as node-name lists, blue = digest edges.
    hash_pos: {anchor: (x, y, text-anchor)} in panel coordinates for digest labels."""
    out = [text(ox + 2, oy + 16, title, 13, INK, weight="600"),
           text(ox + 348, oy + 16, count, 12, BLUE_DEEP, anchor="end", weight="600"),
           text(ox + 2, oy + 40, value_str, 12.5, INK, mono=True)]

    def pt(n):
        return (nodes[n][1] + ox, nodes[n][2] + oy)

    borders, fills = [], []
    for _, polylines in blobs:
        pls = []
        for pl in polylines:
            pts = [pt(n) for n in pl]
            if len(pts) == 1:
                (x, y) = pts[0]
                half = 9 if nodes[pl[0]][0] in ("c", "o") else 0.01
                pts = [(x - half, y), (x + half, y)]
            pls.append(pts)
        b, f = blob_paths(pls)
        borders.append(b)
        fills.append(f)
    out += borders + fills
    for a, b in edges:
        p, q = pt(a), pt(b)
        if (a, b) in blue:
            tp, tq = trim(p, q, 26, 27)
            out.append(line(tp, tq, BLUE_DEEP, 1.7, marker="arr-blue"))
        else:
            tp, tq = trim(p, q, 12, 12)
            out.append(line(tp, tq, EDGE, 1.6))
    for nm, (kind, x, y, lbl) in nodes.items():
        if kind == "c":
            out.append(container_node(x + ox, y + oy, label=lbl))
        elif kind == "o":
            out.append(opaque_node(x + ox, y + oy, label=lbl))
        else:
            out.append(scalar_node(x + ox, y + oy, lbl))
    for bx, by, anchor, btxt in badges:
        out.append(badge(bx + ox, by + oy, btxt, anchor))
    if hashes and hash_pos:
        for anchor, _ in blobs:
            if anchor in hashes and anchor in hash_pos:
                hx, hy, anc = hash_pos[anchor]
                out.append(text(hx + ox, hy + oy, hashes[anchor], 12, MID_INK,
                                anchor=anc, mono=True))
    return out


def svg_special(hashes=None, background=True):
    hashes = hashes or {}
    W, H = 800, 626
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
           f'font-family="{SANS}">', GEN_NOTE, DEFS]
    if background:
        out.append(f'<rect width="{W}" height="{H}" fill="{SURFACE}"/>')
    out.append('<g transform="translate(0,-64)">')

    panels = [
        ("opaque", 45, 100, "Opaque object", "2 entries", "[1, array([8, 9])]",
         {"root": ("c", 170, 90, "[ ]"), "1": ("s", 110, 160, "1"),
          "A": ("o", 230, 160, "arr")},
         [("root", "1"), ("root", "A")],
         [("root", [["1", "root"]]), ("A", [["A"]])],
         {("root", "A")},
         [(230, 128, "middle", "d=&#8734;")],
         {"root": (132, 70, "end"), "A": (230, 198, "middle")}),

        ("propagate", 425, 100, "&#8734; propagates upward", "3 entries", "[1, [2, array([8, 9])]]",
         {"root": ("c", 170, 80, "[ ]"), "1": ("s", 110, 150, "1"),
          "M": ("c", 230, 150, "[ ]"), "2": ("s", 180, 220, "2"),
          "A": ("o", 285, 220, "arr")},
         [("root", "1"), ("root", "M"), ("M", "2"), ("M", "A")],
         [("root", [["1", "root"]]), ("M", [["2", "M"]]), ("A", [["A"]])],
         {("root", "M"), ("M", "A")},
         [(258, 144, "start", "d=&#8734;"), (285, 188, "middle", "d=&#8734;")],
         {"root": (132, 60, "end"), "M": (258, 128, "start"), "A": (322, 224, "start")}),

        ("namedtuple", 45, 380, "Namedtuple vs plain tuple", "3 entries", "[(4, 5), Point(x=4, y=5)]",
         {"root": ("c", 170, 80, "[ ]"), "T": ("c", 110, 150, "( )"),
          "P": ("o", 245, 150, "Pt"), "4": ("s", 75, 220, "4"),
          "5": ("s", 145, 220, "5")},
         [("root", "T"), ("root", "P"), ("T", "4"), ("T", "5")],
         [("root", [["root"]]), ("T", [["4", "T", "5"]]), ("P", [["P"]])],
         {("root", "T"), ("root", "P")},
         [(80, 138, "end", "d=1"), (245, 118, "middle", "d=&#8734;")],
         {"root": (208, 60, "start"), "T": (78, 158, "end"), "P": (245, 188, "middle")}),

        ("empty", 425, 380, "Empty containers", "1 entry", "[1, [], {}]",
         {"root": ("c", 170, 90, "[ ]"), "1": ("s", 100, 160, "1"),
          "E": ("c", 170, 160, "[]"), "D": ("c", 240, 160, "{}")},
         [("root", "1"), ("root", "E"), ("root", "D")],
         [("root", [["1", "root"], ["root", "E"], ["root", "D"]])],
         set(),
         [(170, 197, "middle", "d=0"), (240, 197, "middle", "d=0")],
         {"root": (170, 58, "middle")}),
    ]
    for pid, *args in panels:
        out += vignette(*args, hashes=hashes.get(pid))

    # legend row
    b, f = blob_paths([[(40, 655), (70, 655)]], width=22)
    out += [b, f]
    out.append(text(86, 659, "one storage entry", 11.5, INK2))
    out.append(line((240, 655), (274, 655), BLUE_DEEP, 1.7, marker="arr-blue"))
    out.append(text(286, 659, "&lt;digest&gt; reference", 11.5, INK2))
    out.append(line((430, 655), (464, 655), EDGE, 1.6))
    out.append(text(476, 659, "inlined child", 11.5, INK2))
    out.append(opaque_node(620, 655, w=34, h=18, fs=9.5, label="obj"))
    out.append(text(646, 659, "opaque &#8212; never inlines", 11.5, INK2))

    out.append("</g>")
    out.append("</svg>")
    return "\n".join(out)


def real_hashes():
    """Compute the digest labels for every figure from actual fleche storages.

    Builds the exact layouts the figures depict in :class:`~fleche.storage.ValueMemory`
    stores and shortens each entry's key with the storage's own ``shrink``, so the
    labels in the committed SVGs match what a reader reproducing the layouts in
    ``notebooks/Destructuring.ipynb`` sees.  The depth-figure labels are shrunk
    against the maximally split (``remaining_depth=0``) store: its key set is a
    superset of every other panel's, so the prefixes stay unambiguous everywhere.
    """
    from collections import namedtuple

    import numpy as np

    from fleche.digest import digest
    from fleche.storage import ValueMemory

    def short(storage, key):
        return storage.shrink(key) + "…"

    vm = ValueMemory({})
    k_xs = vm.save([1, [2, 3]])
    k_ys = vm.save([4, [2, 3]])
    dedup = {"xs": short(vm, k_xs), "ys": short(vm, k_ys),
             "shared": short(vm, digest([2, 3]))}

    vm0 = ValueMemory({}, remaining_depth=0)
    vm0.save([[1, 2], [3, [4, 5]]])
    node_values = {"root": [[1, 2], [3, [4, 5]]], "L": [1, 2], "R": [3, [4, 5]],
                   "S": [4, 5], "1": 1, "2": 2, "3": 3, "4": 4, "5": 5}
    depth = {n: short(vm0, digest(v)) for n, v in node_values.items()}

    Point = namedtuple("Point", ["x", "y"])
    arr = np.array([8, 9])
    vm_o = ValueMemory({})
    vm_o.save([1, arr])
    vm_p = ValueMemory({})
    vm_p.save([1, [2, arr]])
    vm_n = ValueMemory({})
    vm_n.save([(4, 5), Point(4, 5)])
    vm_e = ValueMemory({})
    vm_e.save([1, [], {}])
    special = {
        "opaque": {"root": short(vm_o, digest([1, arr])),
                   "A": short(vm_o, digest(arr))},
        "propagate": {"root": short(vm_p, digest([1, [2, arr]])),
                      "M": short(vm_p, digest([2, arr])),
                      "A": short(vm_p, digest(arr))},
        "namedtuple": {"root": short(vm_n, digest([(4, 5), Point(4, 5)])),
                       "T": short(vm_n, digest((4, 5))),
                       "P": short(vm_n, digest(Point(4, 5)))},
        "empty": {"root": short(vm_e, digest([1, [], {}]))},
    }
    return dedup, depth, special


def svg_to_png(svg, zoom=2.0):
    """Rasterize SVG markup for notebook embedding, or ``None`` if no converter.

    The notebook attaches PNG renderings because JupyterLab refuses to render
    ``image/svg+xml`` markdown-cell attachments (SVG can carry scripts).  The
    2x zoom keeps the figures crisp: viewers scale images down to the cell
    width via ``max-width: 100%``.
    """
    import subprocess
    data = svg.encode()
    try:
        return subprocess.run(["rsvg-convert", "-z", str(zoom)], input=data,
                              check=True, capture_output=True).stdout
    except (OSError, subprocess.CalledProcessError):
        try:
            import cairosvg
            return cairosvg.svg2png(bytestring=data, scale=zoom)
        except Exception:
            return None


def refresh_notebook_attachments(svgs):
    """Re-embed PNG renderings of the figures into ``notebooks/Destructuring.ipynb``.

    *svgs* maps SVG filenames to the markup to rasterize — rendered without
    the surface-colored background rect, so the embedded PNGs are transparent
    (the on-disk SVGs keep their background).  The notebook shows the figures
    as ``image/png`` markdown-cell attachments named after the SVGs
    (``dedup_forest.png`` for ``dedup_forest.svg``); whenever the SVGs are
    regenerated, the embedded copies must be refreshed too.  Cells are matched
    by attachment filename, so the notebook structure is left untouched.
    """
    import base64
    import json

    nb_path = os.path.normpath(
        os.path.join(OUT, "..", "..", "notebooks", "Destructuring.ipynb"))
    if not os.path.exists(nb_path):
        return
    png_names = {os.path.splitext(n)[0] + ".png": n for n in svgs}
    with open(nb_path) as fh:
        nb = json.load(fh)
    changed = False
    for cell in nb["cells"]:
        for name in cell.get("attachments", {}):
            if name in png_names:
                png = svg_to_png(svgs[png_names[name]])
                if png is None:
                    print("no SVG-to-PNG converter (rsvg-convert or cairosvg) "
                          "available; notebook attachments NOT refreshed")
                    return
                payload = base64.b64encode(png).decode("ascii")
                cell["attachments"][name] = {"image/png": payload}
                changed = True
    if changed:
        with open(nb_path, "w") as fh:
            json.dump(nb, fh, indent=1)
            fh.write("\n")
        print("refreshed figure attachments in", nb_path)


if __name__ == "__main__":
    dedup_h, depth_h, special_h = real_hashes()
    figures = {"dedup_forest.svg": (svg_dedup, dedup_h),
               "remaining_depth.svg": (svg_depth, depth_h),
               "special_cases.svg": (svg_special, special_h)}
    plain = {}
    for name, (fn, h) in figures.items():
        path = os.path.join(OUT, name)
        with open(path, "w") as fh:
            fh.write(fn(hashes=h))
        plain[name] = fn(hashes=h, background=False)
        print("wrote", path)
    refresh_notebook_attachments(plain)
