name: ty

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: pip install -e .[tests,docs,cloudpickle,sqlalchemy,bagofholding] ty
      - name: Run ty
        run: ty check src
